name: Update Blocked Yandex

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update-blocked-yandex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run the script
        run: |
          cd .github/working
          pip install requests
          python blocked-names-russia.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mv .github/working/blocked-names-russia.txt ./
          git add blocked-names-russia.txt
          git commit -m "⚡ Blocked Names Russia - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin HEAD:main --force || echo "No changes to commit"
